# Package assembly: a MATLAB source tree -> a Julia package skeleton.
#
# Stage 7 of the pipeline. Converts each `.m` file, maps MATLAB `+package` folders to Julia
# submodules, and scaffolds a `Project.toml` (UUID generated by Pkg — never hand-written) plus
# a top-level module that `include`s the converted files.

import Pkg

_jlname(mfile) = string(mfile[1:(end - 2)], ".jl")     # foo.m -> foo.jl

_is_mex(entry) = match(r"\.mex\w+$", entry) !== nothing   # foo.mexa64 / .mexw64 / .mexmaci64 / …

# A compiled MEX has no `.m` source to transpile; copy the binary into the package and emit a
# binding that loads + calls it through Unmex.jl.
function _emit_mex_binding!(srcpath, entry, outdir, imports)
    fname = first(splitext(entry))                        # foo.mexa64 -> foo
    cp(srcpath, joinpath(outdir, entry); force = true)    # binary sits next to its binding
    push!(imports, :Unmex)
    jl = string(fname, ".jl")
    open(joinpath(outdir, jl), "w") do io
        println(io, "# Compiled MEX `", entry, "` — no .m source to transpile; loaded via Unmex.jl.")
        println(io, "import Unmex")
        println(io, "const _", fname, "_mex = Unmex.open_mex(joinpath(@__DIR__, ", repr(entry), "))")
        println(io, fname, "(args...; nargout = 1) = Unmex.call(_", fname, "_mex, args...; nargout = nargout)")
    end
    return jl
end

function _convert_dir_files!(srcdir, outdir, imports)
    includes = String[]
    for entry in sort(readdir(srcdir))
        full = joinpath(srcdir, entry)
        if endswith(entry, ".m")
            out = _jlname(entry)
            r = convert_file(full)
            write(joinpath(outdir, out), r.julia)
            union!(imports, r.imports)
            push!(includes, out)
        elseif _is_mex(entry)
            push!(includes, _emit_mex_binding!(full, entry, outdir, imports))
        end
    end
    return includes
end

# Wire the deps the converted code needs into the generated package. Unregistered/offline deps
# (e.g. Unmex/LibMx behind a firewall) are propagated by *path*: an explicit `dev` mapping wins,
# otherwise any package already `develop`ed in the active environment is `develop`ed into the new
# package too — so a local clone in your Mjolnir env reaches the generated package with no network.
function _wire_deps!(pkgdir, imports, dev)
    isempty(imports) && return
    cur = Dict{String, Any}()                       # snapshot the ACTIVE env before we switch
    for (u, info) in Pkg.dependencies()
        cur[info.name] = (uuid = u, source = info.source, devved = info.is_tracking_path)
    end
    Pkg.activate(pkgdir) do
        for dep in sort!(string.(collect(imports)))
            try
                if haskey(dev, dep)
                    Pkg.develop(Pkg.PackageSpec(path = String(dev[dep])))
                elseif haskey(cur, dep) && cur[dep].devved
                    Pkg.develop(Pkg.PackageSpec(path = cur[dep].source))
                elseif haskey(cur, dep)
                    Pkg.add(Pkg.PackageSpec(name = dep, uuid = cur[dep].uuid))   # uuid-pinned, no registry lookup
                else
                    Pkg.add(dep)
                end
            catch
                @warn "convert_project: could not wire `$dep`; develop/add it into $(pkgdir) manually."
            end
        end
    end
    return
end

# Warn when the generated files in one module scope define the same function signature more than
# once (Julia silently keeps the last). Reuses `_duplicate_funcs` (emit.jl) on the parsed output.
function _warn_duplicate_funcs(scope, jlpaths)
    exprs = Any[]
    for p in jlpaths
        try
            ast = Meta.parseall(read(p, String); filename = p)
            ast isa Expr && append!(exprs, [e for e in ast.args if e isa Expr && e.head === :function])
        catch
        end
    end
    dups = _duplicate_funcs(exprs)
    isempty(dups) && return
    @warn "convert_project: duplicate function definitions in $scope — later definitions overwrite earlier ones; rename or namespace them." duplicates = ["$nm($(join((isempty(t) ? "_" : "::$t" for t in at), ", ")))" for (nm, at) in dups]
    return
end

"""
    convert_project(srcdir, outdir; name, dev=Dict(), audit=false) -> pkgdir

Convert a directory of MATLAB sources into a Julia package under `outdir/name`:

  * each top-level `.m` file -> a converted `src/<file>.jl`, `include`d by the main module;
  * each MATLAB `+pkg/` folder -> a Julia submodule `src/Pkg.jl` (capitalized) that includes
    its converted members;
  * each compiled MEX (`foo.mexa64`/`.mexw64`/`.mexmaci64`/…) has no `.m` source to transpile, so
    the binary is copied in and a binding is generated that loads + calls it via **Unmex.jl**
    (`open_mex`/`call`), with `Unmex` wired as a dependency;
  * `Project.toml` is generated by `Pkg` (real UUID), and the deps the converted code needs are
    wired in (see below).

Dependencies are wired automatically: a package already `develop`ed in your active environment is
`develop`ed into the generated package **by path** (so unregistered/offline deps like `Unmex`/
`LibMx` propagate without a registry or network). Override or supply paths explicitly with
`dev = Dict("Unmex" => "/path/to/Unmex.jl", …)`. Pass `audit = true` to also run
[`audit_project`](@ref) and report functions that are called but defined nowhere in the tree
(likely in folders you still need to add).

Returns the package directory.
"""
function convert_project(
        srcdir::AbstractString, outdir::AbstractString;
        name::AbstractString, dev::AbstractDict = Dict{String, String}(), audit::Bool = false
    )
    pkgdir = joinpath(outdir, name)
    Pkg.generate(pkgdir)
    srcout = joinpath(pkgdir, "src")
    imports = Set{Symbol}()

    includes = _convert_dir_files!(srcdir, srcout, imports)   # top-level .m files
    toplevel_files = String[joinpath(srcout, f) for f in includes]

    for entry in sort(readdir(srcdir))
        full = joinpath(srcdir, entry)
        (isdir(full) && startswith(entry, "+")) || continue
        submod = uppercasefirst(entry[2:end])         # +stats -> Stats
        subdir = joinpath(srcout, submod)
        mkpath(subdir)
        members = _convert_dir_files!(full, subdir, imports)
        _warn_duplicate_funcs("submodule $submod", String[joinpath(subdir, m) for m in members])
        modfile = string(submod, ".jl")
        open(joinpath(srcout, modfile), "w") do io
            println(io, "module ", submod, "\n")
            for m in members
                println(io, "include(", repr(joinpath(submod, m)), ")")
            end
            println(io, "\nend # module ", submod)
        end
        push!(includes, modfile)
    end

    open(joinpath(srcout, string(name, ".jl")), "w") do io
        println(io, "module ", name, "\n")
        for inc in includes
            println(io, "include(", repr(inc), ")")
        end
        println(io, "\nend # module ", name)
    end

    _warn_duplicate_funcs("the top-level module `$name`", toplevel_files)
    _wire_deps!(pkgdir, imports, dev)

    if audit
        rep = audit_project(srcdir)
        if !isempty(rep.unresolved)
            @warn "convert_project: $(length(rep.unresolved)) function(s) are called but defined nowhere in `$srcdir` — you likely need to add the folders that define them. Run `audit_project(\"$srcdir\"; searchpaths=…)` for details." unresolved = sort(collect(rep.unresolved))
        end
    end
    return pkgdir
end
