# Package assembly: a MATLAB source tree -> a Julia package skeleton.
#
# Stage 7 of the pipeline. Converts each `.m` file, maps MATLAB `+package` folders to Julia
# submodules, and scaffolds a `Project.toml` (UUID generated by Pkg — never hand-written) plus
# a top-level module that `include`s the converted files.

import Pkg

_jlname(mfile) = string(mfile[1:(end - 2)], ".jl")     # foo.m -> foo.jl

_is_mex(entry) = match(r"\.mex\w+$", entry) !== nothing   # foo.mexa64 / .mexw64 / .mexmaci64 / …

# A compiled MEX has no `.m` source to transpile; copy the binary into the package and emit a
# binding that loads + calls it through Unmex.jl.
function _emit_mex_binding!(srcpath, entry, outdir, imports)
    fname = first(splitext(entry))                        # foo.mexa64 -> foo
    cp(srcpath, joinpath(outdir, entry); force = true)    # binary sits next to its binding
    push!(imports, :Unmex)
    jl = string(fname, ".jl")
    open(joinpath(outdir, jl), "w") do io
        println(io, "# Compiled MEX `", entry, "` — no .m source to transpile; loaded via Unmex.jl.")
        println(io, "import Unmex")
        println(io, "const _", fname, "_mex = Unmex.open_mex(joinpath(@__DIR__, ", repr(entry), "))")
        println(io, fname, "(args...; nargout = 1) = Unmex.call(_", fname, "_mex, args...; nargout = nargout)")
    end
    return jl
end

function _convert_dir_files!(srcdir, outdir, imports)
    includes = String[]
    for entry in sort(readdir(srcdir))
        full = joinpath(srcdir, entry)
        if endswith(entry, ".m")
            out = _jlname(entry)
            r = convert_file(full)
            write(joinpath(outdir, out), r.julia)
            union!(imports, r.imports)
            push!(includes, out)
        elseif _is_mex(entry)
            push!(includes, _emit_mex_binding!(full, entry, outdir, imports))
        end
    end
    return includes
end

"""
    convert_project(srcdir, outdir; name) -> pkgdir

Convert a directory of MATLAB sources into a Julia package under `outdir/name`:

  * each top-level `.m` file -> a converted `src/<file>.jl`, `include`d by the main module;
  * each MATLAB `+pkg/` folder -> a Julia submodule `src/Pkg.jl` (capitalized) that includes
    its converted members;
  * each compiled MEX (`foo.mexa64`/`.mexw64`/`.mexmaci64`/…) has no `.m` source to transpile, so
    the binary is copied in and a binding is generated that loads + calls it via **Unmex.jl**
    (`open_mex`/`call`), with `Unmex` wired as a dependency;
  * `Project.toml` is generated by `Pkg` (real UUID).

Returns the package directory. Dependency wiring (adding e.g. `LinearAlgebra` to the
generated `Project.toml` when converted code needs it) is not yet automated.
"""
function convert_project(srcdir::AbstractString, outdir::AbstractString; name::AbstractString)
    pkgdir = joinpath(outdir, name)
    Pkg.generate(pkgdir)
    srcout = joinpath(pkgdir, "src")
    imports = Set{Symbol}()

    includes = _convert_dir_files!(srcdir, srcout, imports)   # top-level .m files

    for entry in sort(readdir(srcdir))
        full = joinpath(srcdir, entry)
        (isdir(full) && startswith(entry, "+")) || continue
        submod = uppercasefirst(entry[2:end])         # +stats -> Stats
        subdir = joinpath(srcout, submod)
        mkpath(subdir)
        members = _convert_dir_files!(full, subdir, imports)
        modfile = string(submod, ".jl")
        open(joinpath(srcout, modfile), "w") do io
            println(io, "module ", submod, "\n")
            for m in members
                println(io, "include(", repr(joinpath(submod, m)), ")")
            end
            println(io, "\nend # module ", submod)
        end
        push!(includes, modfile)
    end

    open(joinpath(srcout, string(name, ".jl")), "w") do io
        println(io, "module ", name, "\n")
        for inc in includes
            println(io, "include(", repr(inc), ")")
        end
        println(io, "\nend # module ", name)
    end

    # Wire dependencies the converted code needs (e.g. LinearAlgebra, Unmex for MEX) into the
    # package env. Add individually + resiliently: an unregistered/unavailable dep (e.g. Unmex if
    # not registered) shouldn't abort the whole assembly — the generated files still list it.
    if !isempty(imports)
        Pkg.activate(pkgdir) do
            for dep in sort!(collect(imports))
                try
                    Pkg.add(string(dep))
                catch
                    @warn "convert_project: could not add `$dep` to the generated package; add it manually."
                end
            end
        end
    end
    return pkgdir
end
