# Package assembly: a MATLAB source tree -> a Julia package skeleton.
#
# Stage 7 of the pipeline. Converts each `.m` file, maps MATLAB `+package` folders to Julia
# submodules, and scaffolds a `Project.toml` (UUID generated by Pkg — never hand-written) plus
# a top-level module that `include`s the converted files.

import Pkg

_jlname(mfile) = string(mfile[1:(end - 2)], ".jl")     # foo.m -> foo.jl

function _convert_dir_files!(srcdir, outdir, imports)
    includes = String[]
    for entry in sort(readdir(srcdir))
        endswith(entry, ".m") || continue
        out = _jlname(entry)
        r = convert_file(joinpath(srcdir, entry))
        write(joinpath(outdir, out), r.julia)
        union!(imports, r.imports)
        push!(includes, out)
    end
    return includes
end

"""
    convert_project(srcdir, outdir; name) -> pkgdir

Convert a directory of MATLAB sources into a Julia package under `outdir/name`:

  * each top-level `.m` file -> a converted `src/<file>.jl`, `include`d by the main module;
  * each MATLAB `+pkg/` folder -> a Julia submodule `src/Pkg.jl` (capitalized) that includes
    its converted members;
  * `Project.toml` is generated by `Pkg` (real UUID).

Returns the package directory. Dependency wiring (adding e.g. `LinearAlgebra` to the
generated `Project.toml` when converted code needs it) is not yet automated.
"""
function convert_project(srcdir::AbstractString, outdir::AbstractString; name::AbstractString)
    pkgdir = joinpath(outdir, name)
    Pkg.generate(pkgdir)
    srcout = joinpath(pkgdir, "src")
    imports = Set{Symbol}()

    includes = _convert_dir_files!(srcdir, srcout, imports)   # top-level .m files

    for entry in sort(readdir(srcdir))
        full = joinpath(srcdir, entry)
        (isdir(full) && startswith(entry, "+")) || continue
        submod = uppercasefirst(entry[2:end])         # +stats -> Stats
        subdir = joinpath(srcout, submod)
        mkpath(subdir)
        members = _convert_dir_files!(full, subdir, imports)
        modfile = string(submod, ".jl")
        open(joinpath(srcout, modfile), "w") do io
            println(io, "module ", submod, "\n")
            for m in members
                println(io, "include(", repr(joinpath(submod, m)), ")")
            end
            println(io, "\nend # module ", submod)
        end
        push!(includes, modfile)
    end

    open(joinpath(srcout, string(name, ".jl")), "w") do io
        println(io, "module ", name, "\n")
        for inc in includes
            println(io, "include(", repr(inc), ")")
        end
        println(io, "\nend # module ", name)
    end

    # Wire dependencies the converted code needs (e.g. LinearAlgebra) into the package env.
    if !isempty(imports)
        Pkg.activate(pkgdir) do
            Pkg.add([string(i) for i in sort!(collect(imports))])
        end
    end
    return pkgdir
end
